version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zenturno-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zenturno_dev
      POSTGRES_USER: zenturno_user
      POSTGRES_PASSWORD: zenturno_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - zenturno-network

volumes:
  postgres_data:
    driver: local

networks:
  zenturno-network:
    driver: bridge
